apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: spring-petclinic-2
  labels:
    apps.kubernetes.io/name: spring-petclinic
    app.kubernetes.io/part-of: petclinic-server # Add this for tap-gui
    apps.tanzu.vmware.com/has-tests: true
    apps.tanzu.vmware.com/workload-type: web #Use web for all supply chains. This is outdated(ootb_supply_chain_basic => web, ootb_supply_chain_testing => web-test, ootb_supply_chain_testing_scanning => web-scan)
spec:
  params:
  - name: tekton-pipeline-name
    value: spring-petclinic-tests-pipeline
  source:
    git:
      #url: https://github.com/vdesikanvmware/spring-petclinic-original.git
      url: https://github.com/ybhagwan/spring-petclinic.git
      ref:
        branch: main
  serviceClaims:
    - name: spring-petclinic-db
      ref:
        apiVersion: v1
        kind: Secret
        name: spring-petclinic-db
  env:
  - name: SPRING_PROFILES_ACTIVE
    value: mysql
  - name: JAVA_TOOL_OPTIONS
    value: >
      -Dspring.devtools.restart.enabled=true
      -Dspring.devtools.restart.poll-interval=2s
      -Dspring.devtools.restart.quiet-period=1s
      -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=9005
  resources:
    requests:
      memory: 1Gi
      cpu: 100m
    limits:
      memory: 1Gi
      cpu: 4000m